#source 'https://github.com/CocoaPods/Specs.git'

target 'MBMvc', :exclusive => true do
  pod "MBMvc", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MBMvc", :path => "../"

  pod 'FBSnapshotTestCase'
end
